 version: "2"         # required to adjust maintainability checks
 plugins:
  sonar-java:
    enabled: true

  checks:
    nclock:  # 1.3.1 Module size (software lines of code)
      enabled: true
      config:
        threshold: 400

    complexity: # 1.3.2 Class complexity
      enabled: true
      config:
        threshold: 10

    functions: # 1.3.3 Class Design (only for OO languages)
      enabled: true
      config:
        threshold: 20

    duplicated_lines_density: # 1.3.5 Module internal duplication & 1.4.4 Module external duplication
      enabled: true

    comment_lines_density: # 1.3.6 Code commenting
      enabled: true
      config:
        threshold: 15 

    code_smells: # 1.4.1 Cyclic dependencies & 1.4.2 class coupling
      enabled: true

    # 1.3.4 Module Design (only for non-OO languages, so prob not needed) 
    # 1.4.3 Fan-out (for non-OO languages)

